spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vkr
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  mail:
    protocol: smtps
    host: smtp.gmail.com
    port: 465
    username: tasker.vkr@gmail.com
    password: .E7e2/L7-cN?(}/u
    debug: true